POST http://localhost:5004/api/v1/harbor/replication HTTP/1.1
content-type: application/json

{
    "type": "REPLICATION",
    "occur_at": 1655961008,
    "operator": "event_based",
    "event_data": {
        "replication": {
            "harbor_hostname": "harbor.domain.com",
            "job_status": "Failed",
            "artifact_type": "chart",
            "authentication_type": "basic",
            "override_mode": true,
            "trigger_type": "event_based",
            "execution_timestamp": 1655961007,
            "src_resource": {
                "registry_type": "harbor",
                "endpoint": "http://harbor.domain.com:5002",
                "namespace": "chart-dg"
            },
            "dest_resource": {
                "registry_name": "dg.harbor.com",
                "registry_type": "harbor",
                "endpoint": "http://dg.harbor.com:89",
                "namespace": "chart-dg"
            },
            "successful_artifact": [{
                "type": "chart",
                "status": "Succeed",
                "name_tag": "ale-task-job-executor-supervision [1 item(s) in total]"
            }]
        }
    }
}