POST http://localhost:5004/api/v1/argocd/notify/wechat HTTP/1.1
content-type: application/json

{
    "type": "argocd",
    "operator": "default",
    "event_data": {
        "source": "local-host",
        "app_name": "dev-demo",
        "sync_status": "succeeded",
        "health_status": "Healthy"
    },
    "occur_at": 1613245807
}