name: CI
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
env:
  GO_VERSION: 1.17

jobs: 
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go MOD INIT
        run: |
          go env -w GO111MODULE="on"
          go mod tidy
          git diff --exit-code go.mod
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.47.3
        # run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: Lint
        run: make lint
      - name: Test
        run: make test
        