name: CI
on:
  push:
    branches:
      - dev
      # - main
    paths-ignore:
      - 'README.md'
      - '.json/**'
      - 'doc/**'
      - '.test/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.json/**'
      - 'doc/**'
      - '.test/**'

env:
  GO_VERSION: 1.17
  GOLANGCI_LINT_CACHE: /go/.cache/golangci-lint
  # GOCACHE: /go/.cache/go-build
  # GOMODCACHE: /go/pkg/mod
  # GOPATH: /go

jobs: 
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get Go Ref Path
        id: go-cache-paths
        run: |
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
          echo "::set-output name=go-golangci-lint::/usr/local/bin/golangci-lint"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go MOD INIT
        if: steps.cache-go-mod.outputs.cache-hit != 'true'
        run: |
          go env -w GO111MODULE="on"
          go mod tidy
          git diff --exit-code go.mod
      - name: Cache go modules
        id: cache-go-mod
        uses: actions/cache@v3
        env:
          cache-name: cache-go-modules
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
      - name: Install golangci-lint
        if: steps.cache-golangci-lint-binary.outputs.cache-hit != 'true' 
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.47.3
        # run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: Cache golangci-lint Binary
        id: cache-golangci-lint-binary
        uses: actions/cache@v3
        env:
          cache-name: cache-golangci-lint-binary
        with:
          path: ${{ steps.go-cache-paths.outputs.go-golangci-lint }}
          key: ${{ runner.os }}-golangci-lint-binary-v1.47.3
      - name: Lint
        if: steps.cache-golangci-lint-mod.outputs.cache-hit != 'true'
        run: make lint
      - name: Cache golangci-lint modules
        id: cache-golangci-lint-mod
        uses: actions/cache@v3
        env:
          cache-name: cache-golangci-lint-modules
        with:
          path: ${GOLANGCI_LINT_CACHE}
          key: ${{ runner.os }}-golangci-lint-mod-sail
      - name: Test
        run: |
          test_package=$(go list ./... | grep -vi dingtalk | grep -vi setting)
          go test ${test_package}
      # - name: Docker Bild
      #   run: make docker
          
        